// This file is auto-generated by the grpc_tools_node_protoc_ts plugin.
// Do not edit this file manually.

import * as grpc from "@grpc/grpc-js";
import { MessageTypeDefinition } from "@grpc/proto-loader";

import {
  GreeterClient as _helloworld_GreeterClient,
  IGreeterServer as _helloworld_GreeterService,
} from "@/proto/helloworld_grpc_pb";

type SubtypeConstructor<
  Constructor extends new (...args: any) => any,
  Subtype
> = {
  new (...args: ConstructorParameters<Constructor>): Subtype;
};

export interface ProtoGrpcType {
  helloworld: {
    Greeter: SubtypeConstructor<
      typeof grpc.Client,
      _helloworld_GreeterClient
    > & { service: _helloworld_GreeterService };
    HelloReply: MessageTypeDefinition;
    HelloRequest: MessageTypeDefinition;
  };
}
